FROM node:20-bullseye
WORKDIR /usr/src/app

# copiar package-lock para reproducibilidad
COPY package*.json ./

# instalar dependencias en build time
RUN npm install

# copiar el resto del código
COPY . .

EXPOSE 5173

# comando: ya no hace npm install en cada inicio
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
